### ISSUE TITLE
Issue with Optifine, kinda blackscreen

### ISSUE THREAD

**Issue by derPiepmatz** [lumien231/Custom-Main-Menu#149] opened 2016-10-24 14:30 UTC
Hi, I tried to use custom main menu. I build some fancy menus in MC 1.8 and it worked fine. Now if I try to use **Optifine** with it, some of my main menu will be black. I dunno why.
_without Optfine:_
![20161024162337_1](https://cloud.githubusercontent.com/assets/3590829/19649551/864149e8-9a06-11e6-852b-05d427504d45.jpg)
_with Optfine:_
![20161024162521_1](https://cloud.githubusercontent.com/assets/3590829/19649553/89e0d55a-9a06-11e6-943b-92b8b2c50f85.jpg)
_My mainmenu.json:_
```
{
    "images":
    {
        "title":
        {
            "image" : "rahasia:cmm/Rahasia.png",
            "posX" : -50,
            "posY" : -70,
            "width" : 200,
            "height" : 83,
            "alignment" : "center"
        },
        "BlackBG":
        {
            "image" : "rahasia:cmm/Black.png",
            "posX" : 70,
            "posY" : -400,
            "width" : 200,
            "height" : 800,
            "alignment" : "left_center"
        },
        "VersionImage":
        {
            "image" : "rahasia:cmm/Lite-Version.png",
            "posX" : 78,
            "posY" : 0,
            "width" : 100,
            "height" : 13,
            "alignment" : "center"
        }
    },
    
    "buttons":
    {
        "Piepmatz":
        {
            "text" : "",
            "texture" : "rahasia:cmm/whitePiep.png",
            "posX" : -50,
            "imageWidth" : 1000,
            "imageHeight" : 1000,
            "posY" : -50,
            "width" : 80,
            "height" : 80,
            "alignment" : "bottom_right",
            "action" : 
            {
                "type" : "openGui",
                "gui" : "custom.Piepmatz"
            }
        },
        "RahasiaJoin":
        {
            "text" : "\u00A76Betrete Rahasia",
            "hoverText" : "\u00A76*Betrete Rahasia*",
            "alignment" : "left_center",
            "posX" : 70,
            "posY" : -42,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "connectToServer",
                "ip" : "MINECRAFT.RAHASIA.DE"
            }
        },
        "Website":
        {
            "text" : "Webseite",
            "hoverText" : "*Webseite*",
            "alignment" : "left_center",
            "posX" : 70,
            "posY" : -21,
            "width" : 100,
            "height" : 20,
            "action" : 
            {
                "type" : "openLink",
                "link" : "http://www.minecraft-rahasia.eu"
            }
        },
        "Forum":
        {
            "text" : "Forum",
            "hoverText" : "*Forum*",
            "alignment" : "left_center",
            "posX" : 170,
            "posY" : -21,
            "width" : 100,
            "height" : 20,
            "action" : 
            {
                "type" : "openLink",
                "link" : "http://www.minecraft-rahasia.eu/forum/index.php"
            }
        },

        "More":
        {
            "text" : "\u00A7e...",
            "tooltip" : "Einzelspieler, Mehrspieler & Weiteres",
            "alignment" : "bottom_left",
            "posX" : 2,
            "posY" : -46,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "custom.more"
            }
        },
        "quit":
        {
            "text" : "\u00A7c\u00A7lX",
            "alignment" : "bottom_left",
            "tooltip" : "Spiel verlassen",
            "posX" : 2,
            "posY" : -22,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"

            }
        },
        
        "language":
        {
            "text" : "",
            "tooltip" : "Sprache ändern",
            "alignment" : "bottom_left",
            "posX" : 2,
            "posY" : -68,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "fontSize" : 0.7,
            "posX" : -127,
            "posY" : 2,
            "color" : 6579300,
            "alignment" : "top_right"
        }
    },
    
    "other":
    {
        "background":
        {
            "image" : "rahasia:cmm/LiteBGblur.png",
            "mode" : "fill"
        }
    }
}
```
I hope someone knows what to do now

**Comment by TekkifyChara** [comment] 2016-10-28 15:04
This is either caused by the Fast Render or Fast Math setting, but it would be nice to see a fix for this if possible.

**Comment by lumien231** [comment] 2016-10-28 15:45
Could you post a json (& resources) with which i can reproduce this?

**Comment by TekkifyChara** [comment] 2016-10-28 16:46
With OptiFine_1.10.2_HD_U_D1 and CustomMainMenu-MC1.10.2-2.0.2 (Tekkify Modpack on Technic Launcher if needed) it happens with only Fast Render, I checked.  [Here are the files.](https://mega.nz/#!BA5wTTLR!prjV1d4M5ZvrMAa8pk-6oOgVGAs9swdBjUAnq8MhUGg)

**Comment by derPiepmatz** [comment] 2016-10-29 16:11
Thanks, the thing with Fast Render worked for me to, if you want my ressources, here you go: https://www.dropbox.com/s/gulxxd0uuv2vv26/Optifine%20Black%20Configuration%20Issue.zip?dl=0

**Comment by lumien231** [comment] 2016-10-29 18:14
Figured it out, will be fixed next version

**Closed by lumien231** 2016-10-29 18:14 UTC

**Comment by ubergeek77** [comment] 2017-10-25 20:44
I realize this issue is nearly a year old, but can it be reopened?

This issue still occurs on 1.12.2 with the latest version of Custom Main Menu. The issue goes away when OptiFine's "Fast Render" option is disabled, but that is an invaluable feature to both myself and countless other people.

**Minecraft Version:** 1.12.2
**Forge Version:** 1.12.2-14.23.0.2515
**Custom Main Menu Version:** 2.0.8
**OptiFine Version:** 1.12.2 HD-U-C6

**Comment by lolapkfight** [comment] 2019-05-26 08:08
if anyone use Optifine with Custom Main Menu disable Fast Render and Fast Math to fix black screen.

**Comment by Shmeeb** [comment] 2020-06-02 21:53
@lumien231 would pay for this to be fixed. Shmeeb#4352 (using v2.0.8)
